using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class devis : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        object us = Session["UserID"];
        if (Session["UserID"] == null || Session["RoleId"] == null)
            Response.Redirect("Admin.aspx");
    }
 
    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {
 //    GridView1.AutoGenerateDeleteButton="delete from devis where nom='"+GridView1.
      // for (i = 0; i < GridView1.Rows.Count; i++) 
       
 
    }
   
   
}